Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -55,20 +55,20 @@ jobs:
       if: always()
       
       
-  publish-test-results:
-    name: "Publish Unit Tests Results"
-    needs: build
-    runs-on: ubuntu-latest
-    # the build-and-test job might be skipped, we don't need to run this job then
-    if: success() || failure()
+#   # publish-test-results:
+#     name: "Publish Unit Tests Results"
+#     needs: build
+#     runs-on: ubuntu-latest
+#     # the build-and-test job might be skipped, we don't need to run this job then
+#     if: success() || failure()
 
  
 
-    steps:
-      - name: Download Artifacts
-        uses: actions/download-artifact@v2
-        with:
-          path: artifacts
+#     steps:
+#       - name: Download Artifacts
+#         uses: actions/download-artifact@v2
+#         with:
+#           path: artifacts
 
  
 
@@ -79,15 +79,15 @@ jobs:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     files: reports/*.xml
      
-      - name: reports
-        run: |
+    - name: reports
+      run: |
           ls -lrt $GITHUB_WORKSPACE/reports
           echo "######################Time#################"
            date
-      - name: Publish Unit Test Results
-        uses: mikepenz/action-junit-report@v1
+    - name: Publish Unit Test Results
+      uses: mikepenz/action-junit-report@v1
 #         if: always()
-        with:
+      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           report_paths: reports/**/*.xml   
           
